# Generated by Django 5.1.1 on 2024-09-19 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0002_remove_permissiontache_utilisateur_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='tache',
            old_name='date_debut',
            new_name='date_creation',
        ),
        migrations.RenameField(
            model_name='tache',
            old_name='termine',
            new_name='est_terminee',
        ),
        migrations.AlterField(
            model_name='tache',
            name='titre',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peut_ajouter_tache', models.BooleanField(default=False)),
                ('peut_modifier_tache', models.BooleanField(default=False)),
                ('peut_supprimer_tache', models.BooleanField(default=False)),
                ('peut_marquer_tache_terminee', models.BooleanField(default=False)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AutorisationTache',
        ),
    ]
